title: SpotX
description: Ad-free Spotify desktop client
theme: just-the-docs

url: https://spotx-official.github.io/testsite/

aux_links:
  Template Repository: https://github.com/SpotX-Official/

color_scheme: dark
